version: 0.2

phases:
  pre_build:
    commands:
      - echo "Iniciando la fase de pre_build..."
      - pip install -r requirements.txt
      - echo "Instalación de dependencias completada."

  build:
    commands:
      - echo "Ejecutando pruebas unitarias..."
      - python -m unittest discover -s . -p "test_*.py"

artifacts:
  files:
    - '**/*'
